version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      # Mapeia o mosquitto.conf local para o diretório de config do contêiner
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  pub_sensor_temperatura:
    build: ./pub_sensor_temperatura
    container_name: pub_sensor_temperatura
    depends_on:
      - mosquitto
    restart: unless-stopped

  pub_sensor_umidade:
    build: ./pub_sensor_umidade
    container_name: pub_sensor_umidade
    depends_on:
      - mosquitto
    restart: unless-stopped

  sub_dashboard:
    build: ./sub_dashboard
    container_name: sub_dashboard
    depends_on:
      - mosquitto
    restart: unless-stopped

